version: "3"
services:
  postgres10:
    image: postgres:10
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "9010:5432"
    tty: true
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
  postgres11:
    image: postgres:11
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "9011:5432"
    tty: true
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
  postgres12:
      image: postgres:12
      environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=test
      ports:
        - "9012:5432"
      tty: true
      volumes:
        - ./initdb:/docker-entrypoint-initdb.d

